In [5]:
import numpy as np
import sympy as sp

# Row Echelon form

In [6]:
np.random.seed(50)
A= np.random.randint(0,10,(5,5))
sp.Matrix(A)

Matrix([
[0, 0, 1, 4, 6],
[5, 6, 6, 5, 2],
[7, 4, 3, 6, 4],
[1, 5, 9, 0, 6],
[3, 2, 9, 3, 3]])

In [9]:
def reduce_to_row_echelon_form(matrix):
    rows, cols = matrix.shape
    lead = 0
    for r in range(rows):
        if lead >= cols:
            break
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if cols == lead:
                    break
        matrix[[i, r]] = matrix[[r, i]]
        lv = matrix[r, lead]
        matrix[r] = matrix[r] / lv
        for i in range(rows):
            if i != r:
                lv = matrix[i, lead]
                matrix[i] = matrix[i] - lv * matrix[r]
        lead += 1

reduce_to_row_echelon_form(A)
print("Matrix A in Row Echelon Form:")
print(A)


Matrix A in Row Echelon Form:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
